### ISSUE TITLE
add the #nostr tag to this repo

### ISSUE THREAD

**Issue by gourcetools** [sebastiansieber/nostr-nip05-verification#1]
Would it be possible to add the #nostr tag to this repo

I'll show up in this nice list here:

https://github.com/topics/nostr

**Comment by sebastiansieber** [comment]
Sure! Where do I do that?

**Comment by gourcetools** [comment]
From web go to the repo main page and edit the "About" in top right. Thank you :D

![image](https://user-images.githubusercontent.com/120996278/214191646-fbd169fa-1672-4fac-856d-1894c82372aa.png)

**Comment by sebastiansieber** [comment]
Done.
